### ISSUE TITLE
Keycloak 18 support

### ISSUE THREAD

**Issue by ahmedmozaly-sg** [cloudtrust/keycloak-export#33]
I'm trying to buildhttps://github.com/cloudtrust/keycloak-export/releases/tag/18.0.0-1.0-4 to be able to use it with Keycloak 18

But I'm encountering this error `[ERROR]     Non-resolvable parent POM for io.cloudtrust:keycloak-export-parent:18.0.0: Could not find artifact io.cloudtrust:kc-cloudtrust-module:pom:18.0.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ io.cloudtrust:keycloak-export-parent:18.0.0, /root/ke/pom.xml, line 7, column 13 -> [Help 2]`

Is there some help docs to build it from source?

**Comment by fperot74** [comment]
The modules you are missing are in https://github.com/cloudtrust/cloudtrust-parent project

**Comment by ahmedmozaly-sg** [comment]
Thanks @fperot74 for your response 
Is this the branch I should use https://github.com/cloudtrust/cloudtrust-parent/tree/CLOUDTRUST-4073-upgrade-kc18 ?

**Comment by fperot74** [comment]
You can use master which is the up-to-date version for Keycloak 18. I also just created a kc18 tag
We are currently migrating to Keycloak 20 (may be Keycloak 21) and, when merged, master won't be compatible with Keycloak 18.

**Comment by ahmedmozaly-sg** [comment]
Thanks for the help, I've been able to build & added the jar file under `${keycloak_dir}/providers/`
But when I tried to test `http://localhost:8080/auth/realms/master/export/realm`
I got
```
<body>
	<pre>Cannot GET /auth/realms/master/export/realm</pre>
</body>
```

Is there a way to verify it was loaded in keyloak successfully?

**Comment by fperot74** [comment]
Oops... readme.md is definitively not up-to-date.
You might use install.sh <keycloak-home-folder> to install the module or copy the jar file manually in the KC_HOME/providers folder.
Take care of the /auth. If you are using the default configuration of Keycloak, there is not /auth in the URL.

**Comment by ahmedmozaly-sg** [comment]
I've copied manually to `KC_HOME/providers`
And `http://localhost:8088/auth/realms/master/export/realm` seems to work on now 😄

**Comment by ahmedmozaly-sg** [comment]
Thanks a lot @fperot74 for your great support!

**Comment by ahmedmozaly-sg** [comment]
For future reference, This is an example Dockerfile for building `keycloak-export` from source for Keycloak 18

```

################## Build keycloak export from source until there is offical release for Keycloak 18 ######################
FROM adoptopenjdk/openjdk8 as keycloak-export-build
RUN apt update 
RUN apt install maven tar curl -y

RUN mkdir -p /root/src 
RUN curl -sL https://github.com/cloudtrust/cloudtrust-parent/archive/refs/tags/kc18.tar.gz | tar -zx -C /root/src
RUN curl -sL https://github.com/cloudtrust/keycloak-export/archive/refs/tags/18.0.0-1.0-4.tar.gz | tar -zx -C /root/src/cloudtrust-parent-kc18/kc-cloudtrust-module
RUN cd /root/src/cloudtrust-parent-kc18/kc-cloudtrust-module/keycloak-export-18.0.0-1.0-4/keycloak-export/ && mvn -B -T4 clean package 


################## Configure Keycloak with the export provider ######################
FROM quay.io/keycloak/keycloak:18.0.2 as builder

COPY --from=keycloak-export-build /root/src/cloudtrust-parent-kc18/kc-cloudtrust-module/keycloak-export-18.0.0-1.0-4/keycloak-export/target/keycloak-export-18.0.0.jar /opt/keycloak/providers/keycloak-export-18.0.0.jar

# Register providers
RUN /opt/keycloak/bin/kc.sh build

################## Start the already configured Keycloak ######################

FROM quay.io/keycloak/keycloak:18.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY=edge
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
