### ISSUE TITLE
Keycloak 21 support

### ISSUE THREAD

**Issue by ahmedmozaly-sg** [cloudtrust/keycloak-export#37]
If [keycloak-export](https://github.com/cloudtrust/keycloak-export) built from master, Could it be used with Keycloak 21?

**Comment by fperot74** [comment]
It is currently only compatible with KC18.
We are in process of migrating to a newer version. For internal reasons, it might be KC20

**Comment by ahmedmozaly-sg** [comment]
KC20 is fine with me,
So, It's better to wait for a release from your side as building from master won't work right now with KC20 right?
